project:
  type: website
  output-dir: docs

website:
  title: "LouisaJade.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Resume.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    toc-location: right
    fontcolor: "#000000"
    linkcolor: "#0b40d9"
    
    

editor: visual

