---
title: "Projects"
format: html
---

### **Spring 2023**

#### Oregon State University - Intro to Entomology

In the spring of 2023 I took a class on entomology at Oregon State University. The final project was a creative website on an insect related to our major. My major at the time was marine biology and there are very few marine insects so I settled on one particular insect with little to no previous research done.

[Echthrodesis lamorali: Intertidal Parasitoid Wasp](https://echthrodesislamoraliintertidal.godaddysites.com/)

### **Spring 2024**

#### Colorado State University - CO 301B - Writing in the Disciplines: Sciences

In the spring of 2024 I took a class at Colorado State University that focused on various forms of scientific writing. The final project was a creative personal website to showcase different forms of presenting scientific information. This website also includes a link to access my previous entomology website.

[Personal Website](https://beckettlouisa04.wixsite.com/my-site-1)
